### PR TITLE
Get alloc string

### LINKED ISSUE #245: variable length allocatable string array
Hi, I have a question for allocatable string arrays:

To read a (scalar) string from a JSON structure I **must** use a variable length string, as in:

```fortran
use json_module, only : json_file
use json_kinds, only: json_CK  => CK

character(kind=json_CK, len=:), allocatable :: string
character(kind=json_CK, len=:), allocatable :: string_scalar
type(json_file) :: json

string = '{"string_scalar":"x"}'
call json%get("string_scalar", string_scalar)
```

while if I try to read an array of string by using a variable length (allocatable) string, as in,
```fortran
use json_module, only : json_file
use json_kinds, only: json_CK  => CK

character(kind=json_CK, len=:), allocatable :: string
character(kind=json_CK, len=:), allocatable :: string_array(:)
type(json_file) :: json

string = '{"string_array":["x", "y", "z"]}'
call json%get("string_array", string_array)
```

I get the compiler error (using ``gcc version 6.2.0``):
```
call json%get("string_array", string_array)
               1
Error: Found no matching specific binding for the call to the GENERIC 'get' at (1)
```

While using a fixed length allocatable string, as in, 
```fortran
use json_module, only : json_file
use json_kinds, only: json_CK  => CK

character(kind=json_CK, len=:), allocatable :: string
character(kind=json_CK, len=1), allocatable :: string_array(:)
type(json_file) :: json

string = '{"string_array":["x", "y", "z"]}'
call json%get("string_array", string_array)
```
does the job.

Is the different usage of fixed/variable length strings for reading scalar/array strings from JSON due to the current compiler support of variable length strings?

### PR DESCRIPTION
**Pull request by jacobwilliams**
Added routines for getting an allocatable string vector.
Added a new `string_info` routine.

Fixes #245

### CODE REVIEW

**Comment by jacobwilliams** [comment]
The new Test 25 is failing on Travis with `Fortran runtime error: Integer overflow when calculating the amount of memory to allocate`. I don't get this locally with gfortran 6.1 or ifort. Look into it later.

File: src/json_value_module.F90 [hunk 1]
```diff
@@ -6965,7 +6964,7 @@ subroutine get_chars_from_array(json, element, i, count)
         if (.not. initialized) then
             ! string length long enough to hold the longest one
             allocate( character(kind=CK,len=max_len) :: vec(count) )
```
Comment (jacobwilliams) [inline src/json_value_module.F90]: This is probably causing test to fail on Travis (with the older gfortran). See #265.
